release 3.1.0
renproject/darknode-cli pull request #96
Opened 2021-11-08 22:50 UTC by tok-kkk

- Add support for apple silicon (M1 chip)
- fix installation script not setting the $PATH in some cases 
- fix gcp template syntax error
- move from circleCI to github action 
- github client rate limiting

2021-11-10 22:17 UTC, rahulghangas requested changes
Did an initial pass, didn't find any major issues. How can I test this locally?

2021-11-10 22:17 UTC, rahulghangas commented on artifacts/update.sh
> +  cur_terraform_ver="0.12.24"
Maybe this should not be hardcoded in here? I would rather if it was read from a config file or similar

2021-11-10 22:17 UTC, rahulghangas commented on cmd/down.go
> +	if err := util.NodeExistence(name); err != nil {
I think `ValidateSomething` will be a better suited name here (maybe `ValidateNodeExistence`), since that's the common way to indicate a function that checks and throw/returns an error if validation fails

2021-11-10 22:17 UTC, rahulghangas commented on cmd/main.go
> +var BinaryVersion = "undefined"
Sorry if I missed something, but where is this being populated, and why are we exporting this?

2021-11-10 22:17 UTC, rahulghangas commented on util/github.go
> +func GithubClient(ctx context.Context) *github.Client {
Maybe we need to document somewhere that using an authenticated client requires an environment variable to be set

2021-11-12 10:36 UTC, tok-kkk commented on artifacts/update.sh
> +  cur_terraform_ver="0.12.24"
This is the script to update the darknode-cli tool, usually stored in github release of this repo. 
Don't think there'll be a config file to read from

2021-11-12 10:36 UTC, tok-kkk commented on cmd/down.go
> +	if err := util.NodeExistence(name); err != nil {
Sure. I'll change it back.

2021-11-12 10:37 UTC, tok-kkk commented on cmd/main.go
> +var BinaryVersion = "undefined"
This is populated why building the binaries and publishing the releases.

2021-11-12 10:38 UTC, tok-kkk commented on util/github.go
> +func GithubClient(ctx context.Context) *github.Client {
Yeah, I'll update the README file to include this

2021-11-15 01:01 UTC, jazg approved these changes

2021-11-15 01:02 UTC, jazg commented
Approved as @tok-kkk has resolved the comments from the initial review, and it has been confirmed to be working after testing locally.

2021-11-15 03:13 UTC, merged